version: '3.0'

services:
  grafana:
    container_name: 'parseable-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3010:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/parseable-parseable-datasource
      - ./provisioning:/etc/grafana/provisioning
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    depends_on:
      - alertmanager

  alertmanager:
    image: prom/alertmanager:latest
    container_name: 'parseable-alertmanager'
    ports:
      - 9093:9093/tcp
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
