version: '3.0'

services:
  grafana:
    container_name: 'parseable-datasource'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3010:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/parseable-parseable-datasource
      - ./provisioning:/etc/grafana/provisioning
