{
 "title": "Parseable Meta Dashboard",
 "description": "This dashboard allows users to monitor ingestion and storage details of their Parseable cluster.",
 "tags": [ "Parseable" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ingestor_url",
    "label": "Ingestor URL",
    "query": "select DISTINCT address from pmeta"
   },
   { "name": "time_step_size", "label": "Time Step Size", "query": "15 minutes" }
  ]
 },
 "panels": [
  { "title": "Ingested Data Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ingested events count over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "SELECT DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time, SUM(parseable_events_ingested) AS total_events_ingested  FROM pmeta where address= '$ingestor_url' GROUP BY time  ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Ingested event size over time (JSON size)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time, MAX(parseable_events_ingested_size) as event_size FROM pmeta  where address='$ingestor_url' GROUP BY time  ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Stored data size over time (Parquet size)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time, MAX(parseable_storage_size_data) as data_size FROM pmeta  where address='$ingestor_url' GROUP BY time  ORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Event count - current, lifetime & deleted over time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select a.time,SUM(a.current_events) as current_events, SUM(a.lifetime_events) as lifetime_events, SUM(a.deleted_events) as deleted_events from  (select MAX(parseable_events_ingested) as current_events, MAX(parseable_lifetime_events_ingested) as lifetime_events,   MAX(parseable_deleted_events_ingested) as deleted_events, DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time from pmeta where address='$ingestor_url' group by time order by time) a GROUP BY a.time ORDER BY a.time;"
    }
   ]
  },
  {
   "title": "Event size - current, lifetime & deleted over time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "select a.time, SUM(a.current_events_size) as current_events_size, SUM(a.lifetime_events_size) as lifetime_events_size,  SUM(a.deleted_events_size) as deleted_events_size from  (select MAX(parseable_events_ingested_size) as current_events_size, MAX(parseable_lifetime_events_ingested_size) as lifetime_events_size,   MAX(parseable_deleted_events_ingested_size) as deleted_events_size, DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time from pmeta where address='$ingestor_url' group by time order by time) a group by a.time order by a.time "
    }
   ]
  },
  {
   "title": "Data size - current, lifetime & deleted over time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "select a.time, SUM(a.current_data_size) as current_data_size, SUM(a.lifetime_data_size) as lifetime_data_size,  SUM(a.deleted_data_size) as deleted_data_size from   (select MAX(parseable_storage_size_data) as current_data_size, MAX(parseable_lifetime_storage_size_data) as lifetime_data_size,    MAX(parseable_deleted_storage_size_data) as deleted_data_size, DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time from pmeta where address='$ingestor_url' group by time order by time) a  group by a.time order by a.time;"
    }
   ]
  },
  {
   "title": "Current events ingested per ingestor",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_events_ingested), address from pmeta GROUP BY address"
    }
   ]
  },
  {
   "title": "Staging files count over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time, MAX(parseable_staging_files) as staging_files_count FROM pmeta  where address='$ingestor_url' GROUP BY time  ORDER BY time;"
    }
   ]
  },
  {
   "title": "Staging files size over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "queryText": "SELECT DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time, MAX(parseable_storage_size_staging) as staging_size FROM pmeta where address='$ingestor_url' GROUP BY time  ORDER BY time;"
    }
   ]
  },
  {
   "title": "Current event size (JSON) vs stored data size (Parquet)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT  MAX(parseable_events_ingested_size) as current_events_size ,  MAX(parseable_storage_size_data) as current_data_size  FROM pmeta where address='$ingestor_url' ;"
    }
   ]
  },
  {
   "title": "Lifetime event size (JSON) vs stored data size (Parquet)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT  MAX(parseable_lifetime_events_ingested_size) as lifetime_events_size ,  MAX(parseable_lifetime_storage_size_data) as lifetime_data_size  FROM pmeta where address='$ingestor_url' ;"
    }
   ]
  },
  {
   "title": "Deleted event size (JSON) vs stored data size (Parquet)",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT  MAX(parseable_deleted_events_ingested_size) as deleted_events_size ,  MAX(parseable_deleted_storage_size_data) as deleted_data_size  FROM pmeta where address='$ingestor_url' ;"
    }
   ]
  },
  { "title": "Event and Data Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Current Events Ingested for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_events_ingested) as current_events_ingested_count from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Lifetime Events Ingested for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_lifetime_events_ingested) as total_lifetime_events_ingested from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Events Deleted by Retention for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_deleted_events_ingested) as total_lifetime_events_ingested from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Current Event Size for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_events_ingested_size) as current_events_ingested_size from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Lifetime Event Size for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_lifetime_events_ingested_size) as lifetime_events_ingested_size from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Deleted Event Size for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_deleted_events_ingested_size) as deleted_events_ingested_size from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Current Data Size for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_storage_size_data) as current_events_ingested_size from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Lifetime Data Size for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_lifetime_storage_size_data) as lifetime_events_ingested_size from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Deleted Data Size for - $ingestor_url",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select MAX(parseable_deleted_storage_size_data) as deleted_events_ingested_size from pmeta where address = '$ingestor_url'"
    }
   ]
  },
  {
   "title": "Total Event Size (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select SUM(a.event_size) as event_size from (select MAX(parseable_events_ingested_size) as event_size from pmeta group by address) a"
    }
   ]
  },
  {
   "title": "Total Data Size (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "select SUM(a.storage_size) as storage_size from (select MAX(parseable_storage_size_data) as storage_size from pmeta group by address) a"
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Total Resident Memory Usage Over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "select DATE_BIN('$time_step_size', p_timestamp, NOW()) AS time, MAX(process_resident_memory_bytes) as process_resident_memory_bytes  from pmeta where address='$ingestor_url' group by time order by time;"
    }
   ]
  },
  {
   "title": "Current Memory Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "queryText": "SELECT MAX(process_resident_memory_bytes) AS memory_usage FROM pmeta  WHERE address='$ingestor_url' and p_timestamp >= NOW() - INTERVAL '1 minute'"
    }
   ]
  }
 ]
}