{
 "title": "Parseable Demo Data",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Textual View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Data",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "queryText": "select * from frontend" }
   ]
  },
  {
   "title": "Log View",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "queryText": "select * from frontend" }
   ]
  },
  { "title": "Graphical View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "API Success Rate / Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as Successes from frontend where status ='200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    }
   ]
  },
  {
   "title": "API Failure Rate / Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as Successes from frontend where status <> '200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    }
   ]
  },
  {
   "title": "API Success Rate / Method / Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as POST_successes from frontend where method='POST' and status ='200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    },
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as PUT_successes from frontend where method='PUT' and status ='200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    },
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as GET_successes from frontend where method='GET' and status ='200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    },
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as DELETE_successes from frontend where method='DELETE' and status ='200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    }
   ]
  },
  {
   "title": "API Failure Rate / Method / Second",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as POST_failures from frontend where method='POST' and status <>'200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    },
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as PUT_failures from frontend where method='PUT' and status <>'200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    },
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as GET_failures from frontend where method='GET' and status <>'200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    },
    {
     "queryText": "select date_trunc('second',CAST(datetime AS Timestamp)) as datetime, count(*) as DELETE_failures from frontend where method='DELETE' and status <>'200' group by date_trunc('second',CAST(datetime AS Timestamp))"
    }
   ]
  }
 ]
}